name: Create .env file

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "ENV_VARIABLES=${{ secrets.ENV_VARIABLEs }}" >> .env

      - name: Show .env file
        run: cat .env
